name: "Triage issues on a schedule"

on:
  push:
    paths:
    - .github/workflows/scheduled-triage.yml
  schedule:
    # Once every day at midnight UTC
    - cron: "0 0 * * *"

jobs:
  stale:
    if: startsWith(github.repository, 'Homebrew/')
    runs-on: ubuntu-latest
    steps:
      - name: Mark/Close Stale Issues and Pull Requests
        uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          days-before-stale: 21
          days-before-close: 7
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs.
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs.
          exempt-issue-labels: 'gsoc-outreachy,help wanted,in progress'
          exempt-pr-labels: 'gsoc-outreachy,help wanted,in progress'

      - name: Lock Outdated Threads
        uses: dessant/lock-threads@v2
        with:
          github-token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          issue-lock-inactive-days: 30
          issue-lock-labels: outdated
          pr-lock-inactive-days: 30
          pr-lock-labels: outdated

      - name: Close Support Requests
        uses: dessant/support-requests@v2
        with:
          github-token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          support-label: tmp-support-request
          issue-comment: >
            We use this issue tracker exclusively for bug reports and feature requests.
            Since this issue appears to be a support request, please use
            [GitHub Discussions](https://github.com/homebrew/discussions/discussions) for help.
          close-issue: true
          lock-issue: false
